### ISSUE TITLE
Error: Class of the `.Dtreat` variable is class is not supported.

### ISSUE THREAD

**Issue by romkhun** [grantmcdermott/etwfe#32] opened 2023-04-18 17:14 UTC
Hi Grant,

Thanks for making this package. I would like to use this package on my Ubuntu workstation, but it gives me the following error.

![image](https://user-images.githubusercontent.com/62132647/232853181-1a8d116b-ae8d-47ca-923e-d903e9f81128.png)

I have tried reinstalling R and this package, but the same error occurs. Would there be an easy way to fix it?

![image](https://user-images.githubusercontent.com/62132647/232887200-2a91471e-4ee3-42e3-a35a-3fffdc54b7ea.png)

Thanks again for the package, and I would very much appreciate your help on this issue. Many thanks in advance!

**Comment by grantmcdermott** [comment] 2023-04-19 00:10
Hmmm, that definitely doesn't seem right. Can you please paste your `sessionInfo()`results below.

Also, which version of Ubuntu are you on?

**Comment by romkhun** [comment] 2023-04-19 00:25
Thanks for the quick response, Grant. The sessionInfo() is below. I am using Ubuntu 22.10.

![image](https://user-images.githubusercontent.com/62132647/232934878-a4a1ef4c-6681-4851-b2ea-89982399c037.png)

**Comment by grantmcdermott** [comment] 2023-04-19 23:55
Sorry @romkhun, I'm genuinely stumped for the moment. I can see that you have the latest version of the core packages (namely, `etwfe` and `marginaleffects`). Let me ask this: Did you install the CRAN version of `etwfe` or the development version?

**Comment by romkhun** [comment] 2023-04-21 00:51
Actually, I tried both. 

install.packages("etwfe", repos = "https://grantmcdermott.r-universe.dev")
install.packages("etwfe")

Neither works for me.

**Comment by grantmcdermott** [comment] 2023-04-30 01:30
Hi again @romkhun. So I just tested the package/example on an Ubuntu docker image and everything works as expected. Combined with the fact that all of my CI tests are passing (incl. two on Ubuntu), I think we can surmise that the problem has something to do with your particular system. Sorry, I know that's not helpful but I really can't reproduce this behaviour.

At this point, my next and possibly only best guess is that you have some kind of weird namespace clash. From your `sessionInfo` I can see that you have a bunch of other packages loaded. Can you please try in a fresh session with only `etwfe` loaded?

**Comment by grantmcdermott** [comment] 2023-05-09 16:57
@romkhun See my previous comment. Please let me know if it works in a fresh session without a bunch of other libraries loaded at the same time. Otherwise, I'll have to close since I can't reproduce.

**Comment by grantmcdermott** [comment] 2023-05-11 23:43
Closing since I cannot reproduce this behaviour.

**Closed by grantmcdermott** 2023-05-11 23:43 UTC

**Comment by grantmcdermott** [comment] 2024-01-25 15:53
> Upgrading from insight version 0.19.1 to 0.19.7 solved it for me.

Thanks @jsr-p, that's useful to know. I can easily add `insight >= 0.19.7` to `etwfe`'s Imports. But I'm wondering if this version requirement should rather be done upstream in `marginaleffects`, since this behavior may affect other similar cases. Any thoughts @vincentarelbundock?

**Comment by vincentarelbundock** [comment] 2024-01-25 15:57
Sure, no problem: https://github.com/vincentarelbundock/marginaleffects/commit/42c49a119cf02b00af1076d29788bce064d5a0c0
